### ISSUE TITLE
Upstream some MaxItems==1 annotations

### ISSUE THREAD

**Issue by lukehoban** [pulumi/terraform-provider-aws#19]
We've seen several places where we needed to force MaxItems==1 in our projection.  We should upstream the addition of MaxItems==1 directly in the TF provider, as that is most likely the intended treatment in TF itself, and would avoid the need for us to add customizations here.

See for example: https://github.com/pulumi/pulumi-aws/pull/151.

**Comment by jen20** [comment]
I believe all of these have now been upstreamed. The remaining ones are where we specifically diverge from the Terraform provider to support arrays in future (e.g. load balancers on ECS clusters), and `aws_iot_topic_rule`, which are incorrectly specified in the Pulumi mapping as MaxItemsOne when the underlying TF provider and API support an array.
