### ISSUE TITLE
Upstream fix for deleting lingering Lambda ENIs on Subnet delete

### ISSUE THREAD

**Issue by lukehoban** [pulumi/terraform-provider-aws#4]
Upstream the fixes in https://github.com/pulumi/terraform-provider-aws/commit/3cf80a831663297d431d2e73db9eb32da496fe71.

Mostly likely this is a fix for https://github.com/terraform-providers/terraform-provider-aws/issues/829.

**Comment by pgavlin** [comment]
I suspect that we'll just take https://github.com/terraform-providers/terraform-provider-aws/pull/4884 once it's merged.

**Comment by lukehoban** [comment]
We already took the upstream fixes in place of ours.
