### ISSUE TITLE
Do not print ECR credentials into the debug log

### ISSUE THREAD

**Issue by t0yv0** [pulumi/terraform-provider-aws#62]
When using `pulumi --logtostderr -v=9 preview`, observing the following log output (redacted). It might be good to exclude `AuthorizationToken` from the output since that might be a sensitive datum granting access to the ECR, requiring users to be careful when sharing or posting debug logs.

```
I0517 11:56:18.831880   11496 eventsink.go:59] Reading ECR repository credentials 978293506743
I0517 11:56:18.831903   11496 eventsink.go:62] eventSink::Debug(<{%reset%}>Reading ECR repository credentials 978293506743<{%reset%}>)
I0517 11:56:19.047343   11496 eventsink.go:59] Received ECR repository credentials {
I0517 11:56:19.047383   11496 eventsink.go:62] eventSink::Debug(<{%reset%}>Received ECR repository credentials {<{%reset%}>)
I0517 11:56:19.047658   11496 eventsink.go:59]   AuthorizationData: [{
I0517 11:56:19.047679   11496 eventsink.go:62] eventSink::Debug(<{%reset%}>  AuthorizationData: [{<{%reset%}>)
I0517 11:56:19.047951   11496 eventsink.go:59]       AuthorizationToken: "---------------------",
I0517 11:56:19.047986   11496 eventsink.go:62] eventSink::Debug(<{%reset%}>      AuthorizationToken: "-----------------------",<{%reset%}>)
I0517 11:56:19.048211   11496 eventsink.go:59]       ExpiresAt: 2021-05-18 04:56:19.015 +0000 UTC,
I0517 11:56:19.048232   11496 eventsink.go:62] eventSink::Debug(<{%reset%}>      ExpiresAt: 2021-05-18 04:56:19.015 +0000 UTC,<{%reset%}>)
I0517 11:56:19.048422   11496 eventsink.go:59]       ProxyEndpoint: "https://978293506743.dkr.ecr.us-east-1.amazonaws.com"
I0517 11:56:19.048439   11496 eventsink.go:62] eventSink::Debug(<{%reset%}>      ProxyEndpoint: "https://978293506743.dkr.ecr.us-east-1.amazonaws.com"<{%reset%}>)
I0517 11:56:19.048655   11496 eventsink.go:59]     }]
I0517 11:56:19.048684   11496 eventsink.go:62] eventSink::Debug(<{%reset%}05>    }]<{%reset%}>)
I0517 11:56:19.048887   11496 eventsink.go:59] }
I0517 11:56:19.048910   11496 eventsink.go:62] eventSink::Debug(<{%reset%}>}<{%reset%}>)
```

Suspect line:

https://github.com/pulumi/terraform-provider-aws/blob/00bf1a56cbc32c023d88dbeddc663e6866154c13/aws/data_source_aws_ecr_credentials.go#L59

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by stack72** [comment]
I've pushed https://github.com/pulumi/terraform-provider-aws/commit/5b22ccf02b8b02825563804f96cbed2e7b80c60e which removes the authorization token from the debug details

This will stop this from happening

This will be released in this week's pulumi-aws update
