### ISSUE TITLE
Improve generated class names for WAFv2

### ISSUE THREAD

**Issue by cbcmg** [pulumi/terraform-provider-aws#66]
Hi, I'm finding it quite difficult to work with the wafv2 python bindings. 

* wafv2/_inputs.py is so large intellij won't bother parsing it
* this class name is just a little hard to understand RuleGroupRuleStatementNotStatementStatementOrStatementStatementRegexPatternSetReferenceStatementFieldToMatchSingleQueryArgumentArgs : )

I understand they are generated, and that there is recursive nesting, but maybe some hand tweaking could help here.

Thanks.

**Comment by infin8x** [comment]
Thanks for reporting this! This is due to the schema we inherit from the upstream Terraform provider. We will use this issue to track considering ways to improve that inherited schema.

**Comment by iwahbe** [comment]
This has been fixed in our provider.
